services:

  java:
    build: ./java
    container_name: java-cont
    stdin_open: true
    tty: true

  node:
    build: ./node
    container_name: node-cont
    stdin_open: true
    tty: true

  python:
    build: ./python
    container_name: python-cont
    stdin_open: true
    tty: true

  java-web:
    build: ./web-images/java-web-sb
    container_name: java-web-cont
    ports:
      - "8080:8080"

  node-web:
    build: ./web-images/node-web
    container_name: node-web-cont
    ports:
      - "3000:3000"

  python-web:
    build: ./web-images/python-web
    container_name: python-web-cont
    ports:
      - "5000:5000"
